[tool.poetry]
name = "auto-clicker"
version = "0.0.1"
description = "Small&easy auto-clicker"
authors = ["d.finko <dmit.finn@yandex.ru>"]
repository = "https://github.com/gstr169/auto-clicker"
packages = [
    { include = "auto-clicker" },
]

[tool.poetry.dependencies]
python = "^3.9"
pynput = "^1.7.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
auto-clicker = "auto-clicker.script:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
